apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebsite-deployment
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mywebsite
  template:
    metadata:
      labels:
        app: mywebsite
    spec:
      containers:
      - name: mywebsite
        image: vrush13/kubernetwebsite:latest
        ports:
        - containerPort: 80
